/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinic.booking;

import javax.swing.JOptionPane;

/**
 *
 * @author Hakim
 */
public class frmMain extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmMain.class.getName());

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpChronicIlliness = new javax.swing.ButtonGroup();
        grpGender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblClinicBooking = new javax.swing.JLabel();
        lblNameOfPatient = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblPhysicalAddress = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblEmailAddress = new javax.swing.JLabel();
        lblNextOfKin = new javax.swing.JLabel();
        lblChronicIlliness = new javax.swing.JLabel();
        txtNameOfPatient = new javax.swing.JTextField();
        txtDay = new javax.swing.JTextField();
        txtMonth = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        radMale = new javax.swing.JRadioButton();
        radFemale = new javax.swing.JRadioButton();
        txtPhysicalAddress = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        txtEmailAddress = new javax.swing.JTextField();
        cmbNextOfKin = new javax.swing.JComboBox<>();
        chkPhysical = new javax.swing.JCheckBox();
        chkMental = new javax.swing.JCheckBox();
        chkBoth = new javax.swing.JCheckBox();
        btnDone = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblClinicBooking.setText("Clinic Booking");

        lblNameOfPatient.setText("Name of Patient");

        lblDOB.setText("Date of Birth");

        lblGender.setText("Gender");

        lblPhysicalAddress.setText("Physical Address");

        lblPhoneNumber.setText("Phone Number");

        lblEmailAddress.setText("Email Address");

        lblNextOfKin.setText("Next of Kin");

        lblChronicIlliness.setText("Chronic Illiness");

        txtDay.setText("Day");
        txtDay.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                txtDayComponentHidden(evt);
            }
        });

        txtMonth.setText("Month");

        txtYear.setText("Year");

        grpGender.add(radMale);
        radMale.setText("Male");

        grpGender.add(radFemale);
        radFemale.setText("Female");

        txtPhoneNumber.addActionListener(this::txtPhoneNumberActionPerformed);
        txtPhoneNumber.addPropertyChangeListener(this::txtPhoneNumberPropertyChange);
        txtPhoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPhoneNumberKeyTyped(evt);
            }
        });

        txtEmailAddress.addActionListener(this::txtEmailAddressActionPerformed);

        cmbNextOfKin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Partner", "Child", "Siblings", "Other Blood Relatives" }));

        grpChronicIlliness.add(chkPhysical);
        chkPhysical.setText("Physical");

        grpChronicIlliness.add(chkMental);
        chkMental.setText("Mental");

        grpChronicIlliness.add(chkBoth);
        chkBoth.setText("Both");
        chkBoth.addActionListener(this::chkBothActionPerformed);

        btnDone.setText("Done");
        btnDone.addActionListener(this::btnDoneActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDOB)
                    .addComponent(lblNameOfPatient)
                    .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhysicalAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPhoneNumber)
                    .addComponent(lblEmailAddress)
                    .addComponent(lblNextOfKin)
                    .addComponent(lblChronicIlliness, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDone)
                    .addComponent(lblClinicBooking)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(radMale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtNameOfPatient, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(chkPhysical)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(chkMental)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(chkBoth, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                        .addComponent(cmbNextOfKin, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEmailAddress, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPhoneNumber, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPhysicalAddress, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblClinicBooking)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameOfPatient)
                    .addComponent(txtNameOfPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDOB)
                    .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender)
                    .addComponent(radMale)
                    .addComponent(radFemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhysicalAddress)
                    .addComponent(txtPhysicalAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNumber)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailAddress)
                    .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNextOfKin)
                    .addComponent(cmbNextOfKin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChronicIlliness)
                    .addComponent(chkPhysical)
                    .addComponent(chkMental)
                    .addComponent(chkBoth))
                .addGap(18, 18, 18)
                .addComponent(btnDone)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailAddressActionPerformed

    private void chkBothActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBothActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBothActionPerformed

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        // TODO add your handling code here:
        String name    = txtNameOfPatient.getText();
        String day     = txtDay.getText();
        String month   = txtMonth.getText();
        String year    = txtYear.getText();
        String gender  = radMale.isSelected() ? radMale.getText() : radFemale.isSelected() ? radFemale.getText() : "Not specified";
        String phyAdd  = txtPhysicalAddress.getText();
        String phoneNo = txtPhoneNumber.getText();
        String email   = txtEmailAddress.getText();
        String kin     = (String) cmbNextOfKin.getSelectedItem();
        String illiness = chkPhysical.isSelected() ? chkPhysical.getText() : chkMental.isSelected() ? chkMental.getText() : chkBoth.isSelected() ? chkBoth.getText() : "None";
        
        String formData = "Name of Patient: " + name + "\n" +
                  "Date of Birth: " + day + "/" + month + "/" + year + "\n" +
                  "Gender: " + gender + "\n" +
                  "Physical Address: " + phyAdd + "\n" +
                  "Phone Number: " + phoneNo + "\n" +
                  "Email Address: " + email + "\n" +
                  "Next Of Kin: " + kin + "\n" +
                  "Chronic Illness: " + illiness;
        
        JOptionPane.showMessageDialog(this, formData, "Patient Data", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnDoneActionPerformed

    private void txtPhoneNumberPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtPhoneNumberPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberPropertyChange

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void txtPhoneNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneNumberKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_txtPhoneNumberKeyTyped

    private void txtDayComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtDayComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDayComponentHidden

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmMain().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDone;
    private javax.swing.JCheckBox chkBoth;
    private javax.swing.JCheckBox chkMental;
    private javax.swing.JCheckBox chkPhysical;
    private javax.swing.JComboBox<String> cmbNextOfKin;
    private javax.swing.ButtonGroup grpChronicIlliness;
    private javax.swing.ButtonGroup grpGender;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblChronicIlliness;
    private javax.swing.JLabel lblClinicBooking;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblEmailAddress;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblNameOfPatient;
    private javax.swing.JLabel lblNextOfKin;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPhysicalAddress;
    private javax.swing.JRadioButton radFemale;
    private javax.swing.JRadioButton radMale;
    private javax.swing.JTextField txtDay;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtMonth;
    private javax.swing.JTextField txtNameOfPatient;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtPhysicalAddress;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
